# Use Golang as base image
FROM golang:1.20-alpine

# Set working directory
WORKDIR /app

# Install Air for live reload
RUN go install github.com/cosmtrek/air@v1.40.4

# Copy go modules & install dependencies
COPY go.mod go.sum ./
RUN go mod tidy

# Copy all project files
COPY . .

# Start the server with Air
CMD ["air"]
